apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume1
  labels:
    io.kompose.service: postgres-claim1
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/postgres-volume1
