apiVersion: v1
kind: Service
metadata:
  labels:
    app: samplefdp
  name: samplefdp
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: samplefdp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: samplefdp
  name: samplefdp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samplefdp
  template:
    metadata:
      labels:
        app: samplefdp
    spec:
      containers:
        - name: samplefdp
          image: polimiis/teadal-demo:1.0
          ports:
          - containerPort: 8080
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: "samplefdp-virtual-service"
spec:
  gateways:
  - "teadal-gateway"
  hosts:
  - "*"
  http:
  - match:
    - uri:
        prefix: /samplefdp/
    - uri:
        prefix: /samplefdp
    rewrite:
      uri: /
    route:
    - destination:
        host: samplefdp.default.svc.cluster.local
        port:
          number: 8080
