apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  - name: "80"
    port: 80
    targetPort: 80
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "9000"
    port: 9000
    targetPort: 9000
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
