apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-idp-data-pv
  labels:
    io.kompose.service: postgres-data
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/postgres-data
