apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-idp-volume2
  labels:
    io.kompose.service: postgres-idp-claim2
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/postgres-volume2
