apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  name: teadal-baseline-7
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  local:
    path: /mnt/data/d7
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - teadal-baseline
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
status: {}
