- op: replace
  path: /metadata/name
  value: ollama
- op: replace
  path: /spec/source/path
  value: deployment/plat-app-services/ollama
- op: replace
  path: /spec/project
  value: plat-app-services

