apiVersion: v1
kind: PersistentVolume
metadata:
  name: bpmn-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data-bpmn