apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: bpmn
  name: bpmn
spec:
  ports:
  - name: "8051"
    port: 8051
    targetPort: 8080
  selector:
    io.kompose.service: bpmn
status:
  loadBalancer: {}
