- op: replace
  path: /metadata/name
  value: dspn-webeditor
- op: replace
  path: /spec/source/path
  value: deployment/plat-app-services/dspn-webeditor
- op: replace
  path: /spec/project
  value: plat-app-services
