apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  name: teadal-test-node-1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  local:
    path: /mnt/data/d1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - teadal-test-node
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
status: {}
