apiVersion: v1
kind: Service
metadata:
  name: opa
  labels:
    app: opa
spec:
  ports:
  - name: grpc
    port: 9191
    targetPort: 9191
  selector:
    app: opa

---
# inject data to minio -- instead you should already have your data or create a data store for you synthetic data or start a process to generate the data into the data store of your choice
apiVersion: batch/v1
kind: Job
metadata:
  name: add-bundle-policy-to-minio
  namespace: minio-operator
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: mc
        image: minio/mc:RELEASE.2023-06-23T18-12-07Z
        env:
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: teadal-user-1
                key: CONSOLE_ACCESS_KEY
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: teadal-user-1
                key: CONSOLE_SECRET_KEY
        volumeMounts:
          - name: data-volume
            mountPath: /tmp/basic-teadal-bundle.tar.gz
            subPath: basic-teadal-bundle.tar.gz
        command: ["sh", "-c", "mc alias set rawdata http://teadal-teadal-0.teadal-hl.minio-operator.svc.cluster.local:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY && mc mb --ignore-existing rawdata/opa-policy-bundles && mc --insecure cp /tmp/basic-teadal-bundle.tar.gz rawdata/opa-policy-bundles/basic-teadal-bundle.tar.gz"]
      restartPolicy: Never
      volumes:
       - name: data-volume
         hostPath:
           path: bundles
           type: Directory
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: opa
  labels:
    app: opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
    spec:
      containers:
        - name: opa
          image: openpolicyagent/opa:0.53.1-envoy
          securityContext:
            runAsUser: 1111
          #volumeMounts:
          #- readOnly: true
          #  mountPath: /policy
          #  name: opa-policy
          args:
          - "run"
          - "--server"
          - "--addr=localhost:8181"
          - "--diagnostic-addr=0.0.0.0:8282"
          - "--set=services.default.url=http://minio.minio-operator.svc.cluster.local/"
          - "--set=bundles.default.resource=opa-policy-bundles/bundle.tar.gz"
          - "--set=plugins.envoy_ext_authz_grpc.addr=:9191"
          - "--set=plugins.envoy_ext_authz_grpc.query=data.teadal.allow"
          - "--set=decision_logs.console=true"
          - "--ignore=.*"
          - "--log-format=json-pretty"
          - "--log-level=debug"
          #- "/policy/"
          ports:
          - containerPort: 9191
          livenessProbe:
            httpGet:
              path: /health?plugins
              scheme: HTTP
              port: 8282
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health?plugins
              scheme: HTTP
              port: 8282
            initialDelaySeconds: 5
            periodSeconds: 5
      #volumes:
      #  - name: opa-policy
      #    secret:
      #      secretName: opa-policy
