apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: blazegraph-claim0
  name: blazegraph-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status: {}
