apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-thanos-store-0
  namespace: istio-system
  labels:
    app.kubernetes.io/component: object-store-gateway
    app.kubernetes.io/instance: thanos-store
    app.kubernetes.io/name: thanos-store
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  volumeName: thanos-pv
  resources:
    requests:
      storage: 10Gi
