apiVersion: v1
kind: Service
metadata:
  name: thanos-query
  namespace: istio-system
spec:
  selector:
    app.kubernetes.io/name: thanos-query
  ports:
    - name: http
      protocol: TCP
      port: 9092
      targetPort: 10902
  type: ClusterIP
