apiVersion: v1
kind: Secret
metadata:
  name: teadal.node-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://gitlab.teadal.ubiwhere.com/teadal-tech/teadal.node.git

  # GitLab "Deploy token" to let Argc CD read repo data.
  # See:
  # - https://gitlab.teadal.ubiwhere.com/teadal-tech/teadal.node/-/settings/repository
  username: argocd
  password: _nBfVYgDDqZz7_KnUYXq
