- op: replace
  path: /metadata/name
  value: kubeflow
- op: replace
  path: /spec/source/path
  value: deployment/plat-infra-services/kubeflow
- op: replace
  path: /spec/project
  value: plat-infra-services
