apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  name: ip-10-205-143-198-4
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  local:
    path: /mnt/data/d4
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ip-10-205-143-198
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
status: {}
